module main

struct Vec {
	x int
	y int
}

fn (a Vec) str() string {
	return '{${a.x}, ${a.y}}'
}

// Overload addition operator (+)
fn (a Vec) + (b Vec) Vec {
	return Vec{a.x + b.x, a.y + b.y}
}

// Overload subtraction operator (-)
fn (a Vec) - (b Vec) Vec {
	return Vec{a.x - b.x, a.y - b.y}
}

// Overload equality operator (==)
fn (a Vec) == (b Vec) bool {
	return a.x == b.x && a.y == b.y
}

fn main() {
	a := Vec{2, 3}
	b := Vec{4, 5}
	mut c := Vec{1, 2}

	println('a + b = ${a + b}') // {6, 8}
	println('a - b = ${a - b}') // {-2, -2}

	// c += a is autogenerated from the + overload!
	c += a
	println('c after += a: ${c}') // {3, 5}

	println('a == b: ${a == b}') // false
	println('a == Vec{2, 3}: ${a == Vec{2, 3}}') // true
}
